' Gambas module file


Public Sub main()

  Dim vmem As New ShmMem(1000000)

  With vmem
    !a = 4.67898
    !a = ["this", 2, 4.6]
    !a = 100
    !a = ["this", 2, 4.6]
    .PrintAllInfo()
    !a = "this and that"
    .PrintAllInfo()
    !a = [1, 2, 4.6]
    .PrintAllInfo()
    !a = 1
    .PrintAllInfo()
    !a = [1, 2, 4.6]
    .PrintAllInfo()
    !a = 4.5677
    .PrintAllInfo()
    !a = [1, 2, 4.6]
    !b = [1, 2, 3, 4, 5, 6]
    !b = [!a, "this"]
    For Each v As Variant In !b
      Print v
    Next
  End With

End
