' Gambas module file

Public Sub main()

  Dim MyBlock As New ShmMemBlock(1000000)
  Dim mymem As New ShmManage(MyBlock)
  Dim MyVars As New ShmVarStorage(MyMem)

  Dim MyList As New ShmList(MyVars)

  MyList.add("hello kitty")
  MyList.add("Good bye")

  Dim x As Integer = 1024
  Dim var_x As Long = MyVars.set(x)
  Dim var_y As Long = MyVars.set(5678)
  Dim Var_z As Long = MyVars.set(3.45)
  Dim Var_a As Long = MyVars.set(Now)
  Dim Str_a As Long = MyVars.set("Hello world")

  Dim y As Integer = MyVars[var_x]
  Print y, MyVars[Str_a]

  For Each peach As Variant In MyVars
    Print MyVars.key; "="; Object.Class(peach).name;; MyVars.GetTextType(peach.type);; peach.address
  Next

  MyMem._Print()

End


