' Gambas module file


Public Sub main()
With sharedmem
  
 .Begin(12000)
 Dim ah As File 
 Try ah = Open "/tmp/junk" For Write Create
 Write #1, "hello world\n"
 Try .MyIO = ah.Handle
 ah.handle = .MyIO
 Print "Output sink =";; .MyIO;; "type = "; TypeOf(.MyIO)
 Try Write #11, "this is the Output, of the shortest kind\n"
 If Error Then 
   Print Error.text
 Endif
  
 Try Close .MyIO
 If Error Then 
   Print Error.text
 Endif
 
 Print File.Load("/tmp/junk")
  
  .End()
  
End With
End
