' Gambas module file

Public Sub main()

With sharedmem
.Begin(128000)
Dim c As Variant
Dim d As New TestObjectrdWrClass
c = New TestObjectrdWrClass
Dim e As Variant 

Dim mfile As File
Dim symbols As String[] = Object.Class(c).Symbols
For Each sym As String In symbols
  Try Print Object.GetProperty(c, sym)
Next

.$c = 2
.$c = New TestObjectrdWrClass
Print .$c
.$c.callme()
.d = d
.d.callme()

e = .$c
.$c = New TestObjectrdWr2Class
.$c.callme()

.End()
End With
End
