' Gambas module file

'Fast Unsafe
' notify New Is Not working

Public Sub main()

  With SharedMem
    .Begin()
    .NotifyNew(Me)
    Wait 0.01
    .a = 100
    .NotifyChange("a", Me)
    Wait 1
    .b = 100
    .NotifyChange("b", Me)
    Wait 2
    .a = 200
    .b = 300
    .End()
  End With

End

Public Sub newvar_created(value As Variant, Name As String)

  With sharedmem
    Print "new variable  created:";; Name;; value
  End With

End

Public Sub a_changed(value As Variant, name As String)

  Print name;; value

End

Public Sub b_changed(value As Variant, name As String)

  Print name;; value

End



