' Gambas module file


Public Sub main()

  Dim pp As Pointer
  Dim xx As Pointer
  Dim yy As Pointer
  Dim aa As Pointer
  Dim bb As Pointer
  Dim cc As Pointer

  'Dim data As Variant
  'Dim MyObject As SharedObjectExample = New SharedObjectExample

  Print "Begin Test Alloc Free ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"

  SharedMem.begin(100000)
  Print "Begin of testing"
  SharedMem._print()

  With SharedMem
    pp = .ShmAlloc(500)
    ._print()
    xx = .ShmAlloc(1000)
    ._print()
    yy = .ShmAlloc(800)
    ._print()
    aa = .ShmAlloc(700)
    ._print()
    Print " ===========================================================================================End allocations";; pp;; xx;; yy;; aa

    .ShmFree(xx)
    ._print()
    .ShmFree(aa)
    ._print()
    .ShmFree(yy)
    ._print()
    .ShmFree(pp)
    ._print()
    Print "============================================================================================End Free "

    Print "Begin Reallocation of old blocks"
    xx = .ShmAlloc(900)
    ._print()
    aa = .ShmAlloc(100)
    ._print()
    cc = .ShmAlloc(94)
    ._print()
    bb = .ShmAlloc(1200)
    ._print()
    Print "===========================================================================================Done reallocate blocks";; xx;; aa;; cc;; bb

    ' data = 1234567890
    ' .usermem[cc + .DataOffset] = data
    ' ._print()
    '
    ' data = "This is a string to stick into memory"
    ' .usermem[aa + .DataOffset] = data
    ' Print "=============================================================================================DataString"
    ' ._print()
    '
    ' data = .usermem[cc + .DataOffset]
    ' data = .usermem[aa + .DataOffset]
    '
    ' .usermem[bb + .DataOffset] = MyObject
    '
    ' data = .usermem[bb + .DataOffset]
    '
    ' ._print()
  End With

  SharedMem.End()
  Print "End Test Alloc Free ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"

End

