' Gambas module file

Public Sub main()

  With sharedmem
    Dim a As SharedMemSymbol
    Dim b As New Integer[]
    .Begin()
    For i As Integer = 0 To 10000
      b.Add(i)
    Next
    .a = b

    Print .a[0], .a[5]

    a = .AsObject("a")
    .b = .AsObject("a")

    a.DumpMem()

    Print a[0];; a[1];; a[5]
    Print .b[0];; .b[1];; .b[5]
    Inc a[0]
    Print a[0]

    .b = ["hello", "bye", "snow", "blow"]
    a = .AsObject("b")
    a.DumpMem()
    .End()
  End With

End
