' Gambas module file

Public Sub main()

  Dim Tasks As New NewBGLoader[]
  Dim vmem As New ShmMem(1000000, "jiffy")
  Dim wiggle As Integer = 0
  Dim tmp As NewBGLoader

  With vmem
    !Wiggle = 0
    !AllDone = "No"

    For i As Integer = 0 To 100
      tmp = New NewBGLoader
      Tasks.Add(tmp)
    Next
    Wait 2.00

    Dim counter As Long = 0

    While counter < 11

      wiggle = !Wiggle
      !Wiggle = counter
      Wait 0.5

      If counter Mod 1 = 0 Then
        Print "FG Count = "; counter;; "Wiggle=";; wiggle
      Endif
      If counter = 9 Then
        !AllDone = "Yes"
      Endif

      Inc counter
    Wend
    Print "Completed "

  End With

End
