' Gambas module file

'Public Vars As ShmSymbolTable
Public Vars As ShmMem

Public Sub main()

  Vars = New ShmMem(1128000, "mydata", 800, 0.01, True)
  With vars
    !dog = 0
    !Cow = 0
    !Done = False

    Dim Mtask As New NotifyBGTask As "thetask"
    Wait
    Dim Btask As New NotifyBGTask As "theTask2"
    Wait

    !count = 0
    .Notify("Dog", Me)

    While !count < 100
      !Dog = !count
      !Cow = !count
      Wait 0.03

      !Cow = "hello"
      Wait 0.05

      Inc !count
    Wend

    !Done = True

  End With

  Mtask.Wait()
  BTask.Wait()

  vars.NotifyStop("Cow")
  vars.PrintAllInfo()

End

Public Sub dog_changed(varname As String, value As Variant, TimedOut As Boolean)

  Print Application.id, "FG";; VarName;; "=";; Value

End

Public Sub Cow_changed(varname As String, value As Variant, TimedOut As Boolean)

  Print Application.id, "FG";; VarName;; "=";; Value

End

Public Sub TheTask_Read(value As String)

  Print value

End

Public Sub TheTask2_read(value As String)

  Print value

End
