' Gambas module file

Public Sub main()

  Dim vmem As New ShmMem

  With vmem
    !logit = "this log"
    !lastit = "last log"
    !a = 100
    !b = 500

    !myobj = New NewCopyTestObject
    Dim newObject As Object = !myObj
    !MyObj.value = "this thing"
    Print "Direct Value set";; !MyObj.Value
    !MyObj.value = "This little change"
    Print " Indirect value set ";; !MyObj.value

    .Copy("b", "c")
    If !c = 500 Then
      Print "Copy  worked correctly";; !c
    Endif

    Try .Copy("logit", "lastit")
    If !logit = !lastit Then
      Print "Copy to other variable works!";; Quote(!logit);; Quote(!lastit)
    Endif
    !Lastit = "This no longer matches"
    If !logit <> !lastit Then
      Print "Copy to other variable works!";; Quote(!logit);; Quote(!lastit)
    Else
      Print "Copy failed to make a new copy";; Quote(!logit);; Quote(!lastit)
    Endif

  End With

  'Catch
  ' Error "Copy  Error:";; Error.text

End
