' Gambas module file

Public Sub main()

  Dim vmem As New ShmMem(2850)

  With vmem
    !logit = "this log"
    !lastit = "last log"
    !a = 100
    !b = 500

    .Rename("b", "c")
    If Not .Exist("b") And If !c = 500 Then
      Print "Rename worked correctly";; !c
    Endif

    Try .rename("logit", "lastit")
    If Error Then
      Print "Rename to existing name error works";; Error.text
    Endif

    Try .rename("logits", "lastit")
    If Error Then
      Print "Rename to unknow name error works";; Error.text
    Endif

    Try .rename("logit", "lastitd")
    If Error Then
      Print "Rename When out of memory error works";; Error.text
    Endif

  End With

Catch
  Error "Rename Error:";; Error.text

End
